package typesgen

import "strings"

type Options struct {
	Package string
}

// GenerateGo emits a small, hand-maintained Go model for AI-Map v1.0.
// This is intentionally not schema-derived yet (full codegen can be phased in later).
func GenerateGo(opt Options) []byte {
	pkg := strings.TrimSpace(opt.Package)
	if pkg == "" {
		pkg = "aimap"
	}

	// Deterministic output: no timestamps, stable ordering.
	s := "" +
		"// Code generated by ai-map types (MVP). DO NOT EDIT.\n" +
		"//\n" +
		"// Note: This is a hand-maintained v1.0 model, not schema-derived yet.\n" +
		"package " + pkg + "\n\n" +
		"type AIMap struct {\n" +
		"\tVersion int `yaml:\"version\" json:\"version\"`\n" +
		"\tSystem  System `yaml:\"system\" json:\"system\"`\n" +
		"\n" +
		"\tBoundaries    *Boundaries    `yaml:\"boundaries,omitempty\" json:\"boundaries,omitempty\"`\n" +
		"\tDependencies  *Dependencies  `yaml:\"dependencies,omitempty\" json:\"dependencies,omitempty\"`\n" +
		"\tOwnership     *Ownership     `yaml:\"ownership,omitempty\" json:\"ownership,omitempty\"`\n" +
		"\tRuntime       *Runtime       `yaml:\"runtime,omitempty\" json:\"runtime,omitempty\"`\n" +
		"\tExtensions    map[string]any `yaml:\",inline\" json:\"-\"`\n" +
		"}\n\n" +
		"type System struct {\n" +
		"\tName     string `yaml:\"name\" json:\"name\"`\n" +
		"\tType     string `yaml:\"type,omitempty\" json:\"type,omitempty\"`\n" +
		"\tDomain   string `yaml:\"domain,omitempty\" json:\"domain,omitempty\"`\n" +
		"\tLanguage string `yaml:\"language,omitempty\" json:\"language,omitempty\"`\n" +
		"}\n\n" +
		"type Boundaries struct {\n" +
		"\tEntrypoints map[string][]string `yaml:\"entrypoints,omitempty\" json:\"entrypoints,omitempty\"`\n" +
		"\tModels      []string            `yaml:\"models,omitempty\" json:\"models,omitempty\"`\n" +
		"\tCritical    []string            `yaml:\"critical,omitempty\" json:\"critical,omitempty\"`\n" +
		"}\n\n" +
		"type Dependencies struct {\n" +
		"\tInternal []string `yaml:\"internal,omitempty\" json:\"internal,omitempty\"`\n" +
		"\tExternal []string `yaml:\"external,omitempty\" json:\"external,omitempty\"`\n" +
		"}\n\n" +
		"type Ownership struct {\n" +
		"\tTeam  string     `yaml:\"team,omitempty\" json:\"team,omitempty\"`\n" +
		"\tSlack string     `yaml:\"slack,omitempty\" json:\"slack,omitempty\"`\n" +
		"\tDocs  *DocsLinks `yaml:\"docs,omitempty\" json:\"docs,omitempty\"`\n" +
		"}\n\n" +
		"type DocsLinks struct {\n" +
		"\tADR     string `yaml:\"adr,omitempty\" json:\"adr,omitempty\"`\n" +
		"\tRunbook string `yaml:\"runbook,omitempty\" json:\"runbook,omitempty\"`\n" +
		"}\n\n" +
		"type Runtime struct {\n" +
		"\tEnvironment string   `yaml:\"environment,omitempty\" json:\"environment,omitempty\"`\n" +
		"\tDeploysVia  string   `yaml:\"deploys_via,omitempty\" json:\"deploys_via,omitempty\"`\n" +
		"\tConfigPaths []string `yaml:\"config_paths,omitempty\" json:\"config_paths,omitempty\"`\n" +
		"}\n"
	return []byte(s)
}


